/home/zihan/anaconda3/envs/x/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/zihan/anaconda3/envs/x/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/zihan/anaconda3/envs/x/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/zihan/anaconda3/envs/x/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/zihan/anaconda3/envs/x/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/zihan/anaconda3/envs/x/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
state_spaces:  {'first_0': Box(0, 255, (84, 84, 12), uint8), 'second_0': Box(0, 255, (84, 84, 12), uint8)} ,  action_spaces:  {'first_0': Discrete(18), 'second_0': Discrete(18)}
agents:  ['first_0', 'second_0']
Traceback (most recent call last):
  File "train_pettingzoo_mp_vecenv.py", line 159, in <module>
    main()
  File "train_pettingzoo_mp_vecenv.py", line 154, in main
    fictitious=args.fictitious, test=args.test)
  File "train_pettingzoo_mp_vecenv.py", line 64, in parallel_rollout
    model.train_net()
  File "/home/zihan/research/marl_torch/utils/ppo.py", line 397, in train_net
    self.agents[agent_name].train_net(GAE)
  File "/home/zihan/research/marl_torch/utils/ppo.py", line 296, in train_net
    vs = self.v(s)
  File "/home/zihan/research/marl_torch/utils/ppo.py", line 254, in v
    return self.value.forward(x)  
  File "/home/zihan/research/marl_torch/utils/networks.py", line 128, in forward
    x = x.permute(0,3,1,2)  # change from (N,H,W,C) to (N,C,H,W) for torch
RuntimeError: number of dims don't match in permute
